version: '3'
services:
  python-server:
    build: src/main/python/server
    ports:
      - "5000:80"
    volumes:
      - ./src/main/python/server:/app
    environment:
      - PYTHONUNBUFFERED=FALSE
  vue-client:
    build: src/main/vue/client/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/main/vue/client/:/code
      #- /code/node_modules/
    depends_on:
      - python-server
    